### ISSUE TITLE
[Tracker] Functional Milestones

### ISSUE THREAD

**Issue by liuzix** [liuzix/ticompile#1]
- [x] First JIT query `select v1+v2 from table_1;` with the `Plus` expression JIT'ed.
- [x] Support simple arithmetic expressions of integer and decimal types.
- [ ] Support basic aggregations such as `sum` and `avg`.
- [ ] Support HashJoin.
